name: "Check Testing"
on: push

jobs:
  unit_e2e_testing:
    name: Tests Unit + E2E
    runs-on: ubuntu-latest
    env:
      STANDARD_MIN_COVERAGE: "80"
      APP_ENV: test
      SERVER_ADDRESS: ":8080"
      PORT: 8080
      CONTEXT_TIMEOUT: 2
      DB_HOST: "localhost"
      DB_PORT: 5469
      DB_USER: "postgres"
      DB_PASS: "password"
      DB_NAME: "ionix-test-db-test"
      ACCESS_TOKEN_EXPIRY_HOUR: 2
      REFRESH_TOKEN_EXPIRY_HOUR: 168
      ACCESS_TOKEN_SECRET: "access_token_secret"
      REFRESH_TOKEN_SECRET: "refresh_token_secret"
      IS_SANDOX: false
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.17"
          cache: true
      - name: Delete Fixtures if IS_SANDOX is false
        run: |
            if [ ${IS_SANDOX} == false ]; then
              rm -rf test/fixtures
              echo "Fixtures is deleted"
            fi
      - name: "test"
        run: make test
